name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Format check (optional)
        run: dart format . --set-exit-if-changed
        continue-on-error: true

      - name: Analyze project source (non-fatal)
        run: flutter analyze || true

      # - name: Run tests
      #   run: flutter test
